### PR TITLE
adding new png to image tool link

### PR DESCRIPTION
**Pull request by gingemonster**

### CODE REVIEW

**Comment by NieDzejkob** [comment]
This can already be achieved easily using established tools with less dependencies (`rgbgfx` + `xxd -i` comes to mind). As such, I believe this should be included into MORE.md if at all.

**Comment by gingemonster** [comment]
Perhaps we should add rgbgfx specifically then to the list as I came here to find a program so I didn't have to write my own and couldn't find any in the list that work on a modern version of windows

**Comment by gingemonster** [comment]
can rgbgfx output the tile data and map as c files? Seems to be using 2bpp which I presume is used by Rednex. More than happy to use someone else's tool and ditch mine if I can get it to output something simple to use in plain C?

**Comment by mid-kid** [comment]
`.2bpp` files are raw data you can copy straight to the gameboy's tile memory without any issues. This is language-independent. Look for how to include binary files with whatever toolchain you're using, or whatever `bin2c` program is applicable.

**Comment by NieDzejkob** [comment]
That's why I mentioned `xxd -i`.

**Comment by ISSOtm** [comment]
Yep, `rgbgfx` + `xxd -i` sounds ideal for the job, though it'd be better if RGBDS was able to use stdin as input / stdout as output. Still, that sounds like a better idea than a fully custom tool.
Closing for this reason. If you think it should be added to MORE.md, feel free to make another PR.

**Comment by avivace** [comment]
I have to agree. I don't see the tool having a clear and unique scope.
The task you mentioned can already be accomplished in a number of ways, depending on your preferences and your toolkit, as already mentioned.

However, the list (and the documentation of the dev toolkits)  lacks guides or simple lines explaining this, so we will have to add this, somewhere.

As @ISSOtm suggested, you're welcome to add this tool in MORE.md.

**Pull request closed without merging**
