### PR TITLE
Added two new links for C

### PR DESCRIPTION
**Pull request by gingemonster**
Added a new C Game and link to series of youtube tutorials, both created by me

### CODE REVIEW

**Comment by ISSOtm** [comment]
The last two videos in that playlist are private, why?

**Comment by gingemonster** [comment]
They are just scheduled videos one just gone live, one ready for next week. I try and do one a week but like to get ahead of myself if I can

**Comment by leo-rp** [comment]
I'm new on GB dev , thanks!

**Comment by avivace** [comment]
Looks good to me!

**Pull request merged**
