### PR TITLE
Remove OAM DMA tutorial

### PR DESCRIPTION
**Pull request by ISSOtm**
This tutorial is filled with bad practice, and as such is not awesome.

The section in which it's placed was wrong, too.

### CODE REVIEW

**Comment by avivace** [comment]
Motivation:

https://discordapp.com/channels/303217943234215948/303217943234215948/617630137697173544

```
ISSOtm: @jmooree30 Don't follow that tutorial, it's bad, like, bad
[10:02 AM] ISSOtm: Starting with the absolutely stupidest thing: you can use code as data :scream:
[10:06 AM] ISSOtm:
    ld de, $FF80
    rst $28
    db $00,$0D
    
    push af ; Literally why and why do it HERE where bytes are precious
    ld a, $C1
    ld [$FF46], a ; And that's not even a `ldh`. 1 wasted byte, both in ROM and HRAM, and 1 wasted cycle per call. Plus copying it.
    ld a, 40
.wait
    dec a
    jr nz, .wait
    pop af
    reti ; Can we talk for a moment about how bad this is

    ret
[10:08 AM] ISSOtm: So basically the guy hand-assembled his code, screwed up that process, and you can't even notice because it's obfuscated
[10:08 AM] ISSOtm: Wheeeeeeeee
[10:09 AM] ISSOtm: push af here is unnecessary. It's the "MAKE SURE ALL REGISTERS ARE ALWAYS PRESERVED BECAUSE BAD THINGS MIGHT HAPPEN" mentality, which is directly in conflict with ASM programming (where you're supposed to be efficient and minimalist, from the labguage's very nature)
[10:10 AM] ISSOtm: reti is an AWFUL thing to do here.
[10:11 AM] ISSOtm: Because it means that if you unsuspectingly call hOAMDMA in the middle of your interrupt handler, you'll return with interrupts enabled and no idea about it
[10:11 AM] ISSOtm: This is bad
[10:11 AM] ISSOtm: Because you may need the rest of your handler to be still uninterrupted
[10:12 AM] ISSOtm: The intent was probably that OAM DMA needs to be done with interrupts disabled, otherwise you'll get outside of the HRAM loop; but that doesn't mean to re-enable them once the loop exits...
[10:13 AM] ISSOtm: Moreover, there's an absolutely awful thing there
[10:13 AM] ISSOtm: ld a, $C1
[10:13 AM] ISSOtm: $C1 here is the high byte of the address where your OAM table resides
[10:13 AM] ISSOtm: This forces you to hardcode your shadow OAM's location
[10:14 AM] ISSOtm: And yall know how much I hate hardcoding
[10:14 AM] ISSOtm: However, you can replace that $C1, whether in code or data, with HIGH(wShadowOAM) (assuming that's how you called your shadow OAM)
[10:15 AM] ISSOtm: And boom, no hardcoding anymore! (Just make sure it's ALIGN[8]ed.)
[10:15 AM] ISSOtm: Want even worse? No problem!
[10:16 AM] ISSOtm: The length of what you're copying is hardcoded right before. So you have to modify it if you change the routine's length, such as getting rid of those stupid push af and pop af, or turning that unoptimized ld into a ldh.
[10:17 AM] ISSOtm: Again, that's something RGBASM can take care on its own.
[10:17 AM] ISSOtm: The less things you have to update as well when updating something, the better
[10:17 AM] ISSOtm: HOWEVER
[10:18 AM] ISSOtm: They screwed that up too!
[10:19 AM] ISSOtm: Here's how you'd normally compute the length:
    ld de, $FF80 ; Oh yeah, I forgot to mention, but this is hardcoded as well. Get rid of it.
    rst $28

    dw .codeEnd - .code
.code
    db (...)
.codeEnd
[10:20 AM] ISSOtm: But, remember that the Game Boy's data format is primarily little-endian, so that would produce code similar to db $0D,$00
[10:20 AM] ISSOtm: So instead you'd have to write db HIGH(.codeEnd - .code), LOW(.codeEnd - .code). Yummy.
[10:21 AM] ISSOtm: Okay. And I still have to put the icing on the cake.
[10:21 AM] ISSOtm: The rst $28 thing... is mega dumb.
[10:22 AM] ISSOtm: Let's count the size of the rst's routine: 16 bytes. This means it eats up two rst "slots". That's very inefficient, for a start.
[10:23 AM] ISSOtm: And also, after the code is a dead reti. Why is it there? I don't know, but it'd land at $0038, eating up yet another slot. (And $38 is a particularly useful one.)
[10:24 AM] ISSOtm: The routine itself is bad: first, push and pop bc. Again.
[10:24 AM] ISSOtm: Second, loading the size there. Why? ust do it in the caller code!
[10:25 AM] ISSOtm: Third, using data in the middle of code.
[10:26 AM] ISSOtm: This significantly complicates debugging, as you can't know where the copy function will return (so, for example, you might place a breakpoint in what appears to be code but actually is data just placed in the middle)
[10:26 AM] ISSOtm: It also makes reuse absolutely impossible. Sure, for the OAM DMA it's no big deal, but for other things, it is.
[10:30 AM] ISSOtm: Anyways, here's how to properly do things:
- Get rid of *all things this tutorial told you to
- Use the following OAM DMA routine in ROM, plcae it anywhere, it doesn't matter.
OAMDMA:
    ldh [rDMA], a ; Using labels = good
    ld a, 40
.wait
    dec a
    jr nz, .wait
    ret
OAMDMAEnd:
- Copy it by running the following code:
    ld hl, OAMDMA
    ld bc, (OAMDMAEnd - OAMDMA) << 8 | LOW(hOAMDMA)
.copyDMARoutine
    ld a, [hli]
    ldh [c], a
    inc c
    dec b
    jr nz, .copyDMARoutine
- Allocate some memory in HRAM for it:
SECTION "OAM DMA", HRAM

hOAMDMA::
    ds 8
- Call thusly:
    ld a, HIGH(wShadowOAM)
    call hOAMDMA
[10:31 AM] ISSOtm: Can we also talk for a second how that guy uses semicolons for titles in his tutorial, but always uses colons (??) in all code examples?
```

Thank you for revising these resources, @ISSOtm , I agree on that.

Next time please post the reasons/motivations on the Issues too, so we can keep track of things and know why something has been removed, not just "filled with bad practise, not awesome", since you've already made a write up about that on Discord.

**Comment by ISSOtm** [comment]
Alright, got that. Should I go review some other resources as well? I'll try to keep the ranting down and the tone more neutral this time :p

**Comment by exezin** [comment]
Fascinating that nobody even sent me an @ about this.

**Comment by exezin** [comment]
An update on my previous comment.

The above situation has more or less been resolved (thanks to @avivace), an article based on mine will be published on the new pandoc, I will get appropriate credit where necessary, and I will take the advice of @ISSOtm into consideration and look at updating my original article to reflect that when I get the time.

I will also update my original article with a license that permits sharing/modification given appropriate credit to prevent future situations like this, hopefully next time there's an issue with something, people will contact me directly so that it can be resolved.

**Comment by avivace** [comment]
:tada: Thank you again for taking the time and the patience to go through this and fix the mis-understanding and the mis-crediting the old wiki did on your content. Welcome on board!

**Pull request merged**
