### PR TITLE
Add colored version of Game Boy Crib Sheet

### PR DESCRIPTION
**Pull request by ihonen**
This version is much easier to read and it looks pretty good too. I thought you might want to include it.

### CODE REVIEW

**Comment by ISSOtm** [comment]
This doesn't follow the awesome standard (one link per line, mostly). Why not replace the greyscale version entirely?

Further, the link should be extracted and mirrored, as downloading a ZIP is fairly user-friendly imo.

**Comment by ihonen** [comment]
I was wondering if somewhere out there is a person who, for whatever suspicious reasons, prefers the grayscale version. I also agree that ZIP isn't nice but I have no sensible means to host the file myself at the moment.

I don't mind any changes potentially made to the request at all, I mainly made it to bring the existence of this nicer version to everyone's attention.

**Comment by avivace** [comment]
Hey! Thank you for the link of that version! Anyway, @ISSOtm anticipated me:
I agree it makes no sense in having two different revisions linked. It also seems the version you linked is more recent than the one actually linked, so we should be good to go in replacing it directly.


Here's what I did, so maybe the next time you have a similar suggestion you can handle this directly:
I've downloaded and extracted the zip you provided. I've uploaded the final pdf to our gb-archive repo and it's available here as direct download: https://github.com/gb-archive/salvage/blob/master/misc/GBCribSheet000129.pdf

I'm replacing the link to this one.

Thank you again!

**Comment by ihonen** [comment]
That makes sense. Thanks for handling this and sorry for the hassle. :)

**Comment by avivace** [comment]
No hassle at all! Thank you for noticing and helping

**Comment by stuaxo** [comment]
Maybe it's just firefoxes PDF viewer being weird, but at the very bottom the text seems to come out of the colour and is just on a white background

image

**Comment by avivace** [comment]
Checked with various PDF viewers, I see that too

**Pull request closed without merging**
