### PR TITLE
Add List of GB Flash Cart Vendors and Options

### PR DESCRIPTION
**Pull request by bbbbbr**

### CODE REVIEW

**Comment by eievui5** [comment]
I think it would be nice if the website’s mobile view was improved first. Currently it doesn’t properly fit which makes it difficult to read.

h

**Comment by bbbbbr** [comment]
The mobile view problem seems like an issue that should be opened on the Flash Cart List repo itself, rather than a gating issue for this commit.

Regardless, I'll try a couple different themes. However the theme previewer does not include a page-width-breaking table, so it's hard to tell without redeploying for each one.

**Review by avivace — CHANGES_REQUESTED** [review]
Thanks a lot for the PR, @bbbbbr. And thanks a lot for the useful remarks, @eievui5 !

> The mobile view problem seems like an issue that should be opened on the Flash Cart List repo itself, rather than a gating issue for this commit.

The PR thread is actually the perfect place to discuss about resource in the process of being added, this is where usually we discuss about the "eligibility" of what we're adding, informally (and formally) evaluating if something is "awesome" enough to fit the list.

I do agree with @eievui5, a broken mobile view is a major blocking point if we are to recommend/link a new resource

**Comment by bbbbbr** [comment]
OK. Looked at it a bit and Table overflow is set to scroll now. It's either that or very small table & page text.

Any improvement for mobile beyond those options would require a deeper dive into gh pages themes. TBH probably wouldn't spend the time to make that happen since this is low priority for me.

**Review by avivace — APPROVED** [review]

**Pull request merged**
