### PR TITLE
Fix list of emulators

### PR DESCRIPTION
**Pull request by AntonioND**
The list was clearly wrong.

Also, remove list of emulator development tools. We don't need anyone to develop a better emulator.

### CODE REVIEW

**Comment by AntonioND** [comment]
Also for gbadev: https://github.com/gbdev/awesome-gbadev/pull/20

**Comment by endrift** [comment]
Hm, why no NO$GMB?

**Comment by AntonioND** [comment]
NO$GMB has a 5 minute limit for GBC games. That makes it strictly inferior to VBA.

**Comment by avivace** [comment]
LGTM, long due change

**Review by avivace — APPROVED** [review]

**Comment by AntonioND** [comment]
As much as I like this change, the amount of hate mail and threats I've received is too big to justify the merge. I would end up with no cash, and actually using a GB for my day to day work, or maybe a Pentium 1 computer with Windows 98. I'm sorry, but I will need to close this. It's too soon, people are not ready for this change.

**Comment by endrift** [comment]
I could probably scrounge up a Pentium 3 if that helps

**Pull request closed without merging**
