### PR TITLE
Add CI workflow with awesome-lint

### PR DESCRIPTION
**Pull request by avivace**
This work by @svendahlstrand looks good to me.

However, I'd very much like to customise the rules the linter is applying, disabling some and adding some more. What should be the preferred approach here? Should we fork the awesome-lint npm package and apply our modifications to our fork?

### CODE REVIEW

**Comment by svendahlstrand** [comment]
Thanks, glad you liked it.

I'm personally not a big fan of maintaining forks and try to avoid it when I can. If the changes we want to make could benefit others, I would like to see the work applied upstream instead.

On the other hand, if the added rules are highly specific to us, maybe they could just exist as tiny scripts that are executed during CI? Similar to my old [HTTP status script](https://github.com/gbdev/awesome-gbdev/blob/master/scripts/urls-http-status).

That said, I'm not aginst forking `awesome-lint` if there's a need. What rules do you want to add and remove?

**Comment by avivace** [comment]
I do not want rules enforcing the max depth or linking in any way to the awesome-lists movement. We do backlink but I do not want a badge. I do not want the ToC in the position enforced by the linter , ...

The HTTP script should run periodically, not on commit events..

If we can tune this correctly based on our current criteria this can become a very useful moderation and tool.

Each rule is in a separate file so our "fork" would essentialy be a specification on which rules apply. Of course any improvement on the existing rules can go upstream.

**Comment by svendahlstrand** [comment]
Okay, that leaves us with a TODO like this:

- [ ] Bend the rules to our liking in a separate fork of `awesome-lint`.
- [ ] Start using the fork in the workflow/action.
- [ ] Remove my old HTTP status script (`awesome-lint` checks for dead links).
- [ ] Make the workflow run on commit **and** periodically (daily?) to catch broken links between commits.

I will gladly fix the last three items on that list of you, @avivace, or someone else provides the fork.

**Comment by ISSOtm** [comment]
Why don't the awesome list rules apply to us specifically?

**Comment by svendahlstrand** [comment]
> Why don't the awesome list rules apply to us specifically?

That thought crossed my mind as well. Guess we should drop the awesome-part if we aren't going to live up to the requirements?

**Comment by ISSOtm** [comment]
I don't think that would be a good idea, personally.

**Comment by svendahlstrand** [comment]
No, me neither. I would love it if we could follow the rules: no fork needed and the added benefit of being part of the awesome community.

What drawbacks do you see with living up to the awesome requirements, @avivace?

**Comment by avivace** [comment]
This list was never started as an "awesome list", it was initially a conversion of a blog post collecting resources.

I don't want this page to be limited and constrained by those rules, this is not only a collection of resources but essentialy served (and got popular) as landing page for the gbdev community, redirecting to various communities and related projects AND linking awesome resources. We have badges and video players too, in the [web version](https://gbdev.github.io/list.html).

Sometimes, the list need to have a greater depth to better represent the variety of the topic. I also don't want a "standard layout" in which we must place the ToC before the introductory links.

I intend these rules only as guidelines and in fact we've been always linked in the [awesome collection](https://github.com/sindresorhus/awesome) without ever adding a badge. If the mantainers decide to enforce the rules we can discuss this again to keep appearing the original list.

**Comment by svendahlstrand** [comment]
Thanks for elaborating, @avivace.

**Comment by avivace** [comment]
@svendahlstrand Can you give me commit access on your fork? Since I've opened this PR for you I can't add commits on this without re-forking.

Anyway, the "upstream" awesome-lint package is itself a collection of rules from other sources too so I don't see any problem in customising our rule set. We can merge updates to the rules we are using from upstream easily (upstream being the markdown linter or the `awesome-lint` package)

**Comment by svendahlstrand** [comment]
> Can you give me commit access on your fork? 

I've sent an invite now.

**Comment by stuaxo** [comment]
> This list was never started as an "awesome list", it was initially a conversion of a blog post collecting resources.
> 
> I don't want this page to be limited and constrained by those rules, this is not only a collection of resources but essentialy served (and got popular) as landing page for the gbdev community, 

^ It would be good to say this in the docs somewhere :)

**Comment by avivace** [comment]
Please note that this is a mere interpretation of what happened and the traffic direction from this page. We can however (try to) redirect this if we feel the need to.

Noting this in the docs would mean we approve (or want to enforce) these considerations. This is community mantained and could change in the future, e.g. assuming a more formal ruleset

**Comment by stuaxo** [comment]
Good point also best to avoid fossilization through process.

**Pull request merged**
