### PR TITLE
Split the list in EMULATORS and MORE, remove some resources, add more Contribution Policies

### PR DESCRIPTION
**Pull request by avivace**

### CODE REVIEW

**Comment by jedahan** [comment]
I really like it when awesome lists are all on one page, its easier to search and skim for what you are looking, and more of a judgement call to figure out what should be split out and what shouldn't.

All the changes except for splitting onto multiple pages look great. Why not have MORE.md just be 'education' and keep the emulators section?

**Comment by avivace** [comment]
1. The emulator list could become huge and make the list really long/harder to skim if you are not using the index to navigate it (just scrolling it).

2. Keeping the Emulators in the main list also implies that we merge them with the main emulator section (the one mentioning the `important` ones) so we have to clearly declare/highlight the more important, useful and complete ones, then list all the others.

3. Consider that a "built" version of the list (jekyll/github pages), in HTML, could potentially include each sub list and be one page only. This is WIP and I definitely want to have a "web version".

4. `MORE` shall not be in the main list, as it could potentially include everything tagged `gbdev` making the list useless. This is a _curated_ list, not a database of everything tagged gbdev.

**Comment by avivace** [comment]
So, on the MORE part we agree. What about the Emulators? Some alternatives:

1. (solution actually implemented in this PR) Keep the 5-6 main emulators in the main list and move everything else in EMULATORS
2. Keep them in the main list but apply requisites to be added there. The other WIP/not working/not in decent state/not particular emulators go in MORE

**Comment by jedahan** [comment]
I like proposition #2 - one thing I like about awesome lists is most of the time, everything on the list is *awesome*, not just great or kinda awesome for this one specific thing. Think "if you were talking with a friend about the best emulators for gameboy development, which 3 would you mention and why?", something along those lines.

**Comment by avivace** [comment]
Yep, makes sense. So we will split emulators, define a set of rules and gradually promote the deserving ones to the main list.

Still, the problem of differentiating "useful emulators with debugging features for developing homebrews" and  "good implemented and accurate emulators" for reference of for accuracy emulation stands.

**Pull request merged**
