### PR TITLE
Adds a link to a series of French articles about GameBoy programing using GBDK

### PR DESCRIPTION
**Pull request by flozz**
I am writing a series of article about GameBoy development in French. Please merge if you think that non-english resource can be useful, do not hesitate to reject the PR else :)

The link I added points to the first article of the series, there is a ToC that list the next articles → https://blog.flozz.fr/2018/10/01/developpement-gameboy-1-hello-world/

### CODE REVIEW

**Comment by caiotava** [comment]
Great job, plz translate this to English =).

**Comment by flozz** [comment]
@caiotava it would be nice to have an english translation of the articles, but I have no time to do it myself :(

**Comment by ISSOtm** [comment]
We're currently dicussing this, and the main point is that we're not too hot on having non-English resources in the main document. That said, we have Spanish resources already, so they should be moved as well.

**Comment by flozz** [comment]
Your are right, creating separated documents for non-english resources can be a good idea :)

**Comment by SteveProXNA** [comment]
@caiotava when I open https://blog.flozz.fr/2018/10/01/developpement-gameboy-1-hello-world in Google Chrome I am prompted to translate this page to English... great tutorial!

**Comment by avivace** [comment]
Updated the policy to include english resources only:
https://github.com/gbdev/awesome-gbdev/commit/01ab9377abf0bc665338453dd1fc63431537f658#diff-6a3371457528722a734f3c51d9238c13


Meanwhile, I've added the link to the MORE.md file. Feel free to open another PR when you have an english translation.

**Pull request closed without merging**
