### PR TITLE
Remove link to official manual from Nintendo

### PR DESCRIPTION
**Pull request by AntonioND**

### CODE REVIEW

**Comment by pinobatch** [comment]
For the record, this PR is a follow-up to [this comment](https://github.com/gbdev/pandocs/issues/81#issuecomment-727315109) on gbdev/pandocs#81.

**Comment by avivace** [comment]
I don't have a strong opinion on this. 

The manual shouldn't be online, but we are not hosting it or promoting its usage, it's mainly there for *historical reasons*.
It has been superseded by other stuff for while, now.

Are those historical reasons worth the risk? Probably not.

@ISSOtm maybe can you help us on this?

**Comment by ISSOtm** [comment]
Does anyone have any idea what linking to it would make us liable for? I don't mean what they *think* would be, but what law is relevant, etc.
First question to ask would probably be which jurisdiction's law we should look at... GitHub's, since it's hosting the code? :S

**Comment by avivace** [comment]
I gave this a thought and I honestly don't see a single upside of keeping such type of content up

**Review by avivace — APPROVED** [review]

**Pull request merged**
